/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  description?: string
  journalDescription?: string
  logo?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    credit?: string
    _type: 'image'
  }
  favicon?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  url?: string
  social?: {
    twitter?: string
    facebook?: string
    instagram?: string
    linkedin?: string
    github?: string
  }
  footer?: {
    copyright?: string
    sections?: Array<{
      title?: string
      links?: Array<{
        title?: string
        url?: string
        external?: boolean
        _key: string
      }>
      _type: 'footerSection'
      _key: string
    }>
  }
  seo?: Seo
}

export type Seo = {
  _type: 'seo'
  metaTitle?: string
  metaDescription?: string
  openGraphImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    credit?: string
    _type: 'image'
  }
  keywords?: Array<string>
  noIndex?: boolean
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Resource = {
  _id: string
  _type: 'resource'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  url?: string
  summary?: string
  image?: string
  addedDate?: string
  status?: 'inbox' | 'reviewed' | 'published' | 'rejected'
  mediaType?: 'article' | 'book' | 'video' | 'podcast' | 'tool' | 'other'
  sourceDomain?: string
  normalizedUrl?: string
  tags?: Array<string>
}

export type AuthorReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'author'
}

export type CategoryReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'category'
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  author?: Array<
    {
      _key: string
    } & AuthorReference
  >
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    credit?: string
    _type: 'image'
  }
  categories?: Array<
    {
      _key: string
    } & CategoryReference
  >
  publishedAt?: string
  excerpt?: string
  featured?: boolean
  body?: BlockContent
  seo?: Seo
}

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'blockquote'
      listItem?: 'bullet'
      markDefs?: Array<{
        href?: string
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      caption?: string
      credit?: string
      _type: 'image'
      _key: string
    }
  | {
      language?: 'javascript' | 'typescript' | 'html' | 'css' | 'python' | 'json' | 'bash'
      code?: string
      _type: 'codeBlock'
      _key: string
    }
>

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  mainImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    caption?: string
    credit?: string
    _type: 'image'
  }
  excerpt?: string
  body?: BlockContent
  showInNavigation?: 'true' | 'false'
  navigationOrder?: number
  speakingEngagements?: Array<{
    title?: string
    date?: string
    type?:
      | 'speaking'
      | 'writing'
      | 'interview'
      | 'podcast'
      | 'workshop'
      | 'conference'
      | 'blog'
      | 'article'
    url?: string
    description?: string
    _type: 'engagement'
    _key: string
  }>
  seo?: Seo
}

export type Link = {
  _id: string
  _type: 'link'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  url?: string
  sourceDomain?: string
  normalizedUrl?: string
  summary?: string
  image?: string
  addedDate?: string
}

export type EbirdBirding = {
  _id: string
  _type: 'ebirdBirding'
  _createdAt: string
  _updatedAt: string
  _rev: string
  mapPageTitle?: string
  mapPageIntroduction?: BlockContent
  lifeListPageTitle?: string
  lifeListIntroduction?: BlockContent
  mapDataSource?: 'hotspots' | 'region'
  hotspotCodes?: string
  regionCode?: string
  lifeListLocationId?: string
  recentDaysBack?: number
  maxObservationsToFetch?: number
  defaultMapLatitude?: number
  defaultMapLongitude?: number
  defaultMapZoom?: number
  seoMap?: Seo
  seoLifeList?: Seo
}

export type Homepage = {
  _id: string
  _type: 'homepage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  hero?: {
    title?: string
    subtitle?: string
    primaryButton?: {
      text?: string
      url?: string
    }
    secondaryButton?: {
      text?: string
      url?: string
    }
  }
  seo?: Seo
}

export type Category = {
  _id: string
  _type: 'category'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  description?: string
  color?: 'blue' | 'green' | 'red' | 'yellow' | 'purple' | 'pink' | 'gray'
}

export type Author = {
  _id: string
  _type: 'author'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: string
  slug?: Slug
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    credit?: string
    _type: 'image'
  }
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      href?: string
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  email?: string
  website?: string
  social?: {
    twitter?: string
    linkedin?: string
    github?: string
  }
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | SiteSettings
  | Seo
  | SanityImageCrop
  | SanityImageHotspot
  | Resource
  | AuthorReference
  | CategoryReference
  | Post
  | BlockContent
  | Slug
  | Page
  | Link
  | EbirdBirding
  | Homepage
  | Category
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
