import type {SpecimenPaletteId} from './palettes'
import type {AxisCoord, VariableFontKey} from './variableFonts'

export type EmotionId =
  | 'calm'
  | 'urgent'
  | 'playful'
  | 'solemn'
  | 'warm'
  | 'clinical'
  | 'nostalgic'
  | 'bold'
  | 'anxious'
  | 'romantic'

export type EmotionSurface = 'light' | 'mist' | 'warm' | 'dark' | 'ink'

export type EmotionEntry = {
  id: EmotionId
  label: string
  synonyms: string[]
  /** Primary variable font for this emotion. */
  fontKey: VariableFontKey
  /** Featured look at intensity 50. */
  coordinate: AxisCoord
  /** Look at intensity 100 (subdued is mirrored toward defaults at 0). */
  intense: AxisCoord
  italic?: boolean
  transform?: 'none' | 'uppercase'
  /** Switchable alternate variable fonts. */
  alternateFontKeys: VariableFontKey[]
  /** Fallback chrome when no Coolors palette is set. */
  surface: EmotionSurface
  /** Optional Coolors-backed specimen palette (overrides surface vars). */
  paletteId?: SpecimenPaletteId
  /** Default editable specimen text. */
  specimenWord: string
  reason: string
}

export const EMOTION_CATALOG: EmotionEntry[] = [
  {
    id: 'calm',
    label: 'Calm',
    synonyms: [
      'peaceful',
      'serene',
      'quiet',
      'soft',
      'gentle',
      'tranquil',
      'relaxed',
      'calm',
      'calming',
      'mellow',
      'soothing',
      'still',
      'restful',
      'zen',
      'meditative',
      'balanced',
      'composed',
      'easygoing',
      'laid back',
      'chill',
      'peaceful quiet',
      'fuzzy',
      'fuzz',
      'plush',
      'cushioned',
      'hazy',
      'blurry',
      'cloud',
      'airy',
      'feathery',
      'muted soft',
      'subtle',
      'natural',
      'welcoming',
      'welcome',
      'understated',
      'elegant quiet',
      'collected',
      'timeless',
    ],
    fontKey: 'fraunces',
    coordinate: {wght: 340, opsz: 40, SOFT: 60, WONK: 0},
    intense: {wght: 520, opsz: 72, SOFT: 85, WONK: 0},
    transform: 'none',
    alternateFontKeys: ['bricolage', 'robotoFlex', 'shantell'],
    surface: 'light',
    paletteId: 'neutral-elegance',
    specimenWord: 'Calm',
    reason: 'Soft Fraunces with open optical size reads quiet without going precious.',
  },
  {
    id: 'urgent',
    label: 'Urgent',
    synonyms: [
      'intense',
      'pressing',
      'loud',
      'alert',
      'immediate',
      'critical',
      'tense',
      'urgent',
      'urgency',
      'hurry',
      'rushed',
      'rush',
      'asap',
      'deadline',
      'breaking',
      'alarm',
      'alarming',
      'emergency',
      'crisis',
      'demanding',
      'insistent',
      'forceful',
      'high stakes',
      'time sensitive',
      'angry',
      'anger',
      'furious',
      'fury',
      'rage',
      'enraged',
      'mad',
      'irritated',
      'irate',
      'hostile',
      'hostility',
      'aggressive',
      'aggression',
      'wrath',
      'outraged',
      'pissed',
      'fiery',
      'fire',
      'flame',
      'flames',
      'burning',
      'heated',
      'hot',
      'volcanic',
    ],
    fontKey: 'bricolage',
    coordinate: {wght: 700, wdth: 78, opsz: 48},
    intense: {wght: 800, wdth: 75, opsz: 72},
    transform: 'uppercase',
    alternateFontKeys: ['anybody', 'robotoFlex', 'nabla'],
    surface: 'dark',
    paletteId: 'fiery-ocean',
    specimenWord: 'NOW',
    reason: 'Condensed Bricolage with heavy weight pushes speed and insistence.',
  },
  {
    id: 'playful',
    label: 'Playful',
    synonyms: [
      'fun',
      'joyful',
      'whimsical',
      'lighthearted',
      'curious',
      'bouncy',
      'cheerful',
      'playful',
      'play',
      'happy',
      'happiness',
      'silly',
      'quirky',
      'cheeky',
      'lively',
      'upbeat',
      'bright',
      'sparkly',
      'bubbly',
      'comic',
      'carefree',
      'delightful',
      'kids',
      'childlike',
      'vibrant',
      'candy',
      'pop',
      'colorful',
      'zesty',
    ],
    fontKey: 'recursive',
    coordinate: {wght: 640, slnt: -6, CASL: 1, CRSV: 1, MONO: 0},
    intense: {wght: 850, slnt: -12, CASL: 1, CRSV: 1, MONO: 0},
    transform: 'none',
    alternateFontKeys: ['shantell', 'anybody', 'nabla'],
    surface: 'mist',
    paletteId: 'candy-pop',
    specimenWord: 'Play',
    reason: 'Casual Recursive with cursive lean feels friendly and bouncing.',
  },
  {
    id: 'solemn',
    label: 'Solemn',
    synonyms: [
      'serious',
      'formal',
      'dignified',
      'grave',
      'ceremonial',
      'stately',
      'reverent',
      'solemn',
      'somber',
      'sombre',
      'funeral',
      'memorial',
      'respectful',
      'traditional',
      'classical',
      'institutional',
      'authoritative',
      'monumental',
      'weighty',
      'austere',
      'stoic',
      'dramatic',
      'drama',
      'theatrical',
      'evening',
      'twilight',
      'ceremonial drama',
    ],
    fontKey: 'fraunces',
    coordinate: {wght: 700, opsz: 96, SOFT: 20, WONK: 0},
    intense: {wght: 850, opsz: 144, SOFT: 5, WONK: 0},
    transform: 'none',
    alternateFontKeys: ['bricolage', 'robotoFlex', 'workbench'],
    surface: 'mist',
    paletteId: 'magenta-dream',
    specimenWord: 'Solemn',
    reason: 'High-contrast Fraunces display optical size carries ceremony and weight.',
  },
  {
    id: 'warm',
    label: 'Warm',
    synonyms: [
      'cozy',
      'inviting',
      'friendly',
      'human',
      'approachable',
      'earthy',
      'hospitable',
      'warm',
      'warmth',
      'welcoming',
      'comfort',
      'comfortable',
      'homey',
      'homely',
      'organic',
      'natural',
      'craft',
      'handmade',
      'amber',
      'sunset',
      'hearth',
      'subtle',
      'latte',
      'taupe',
      'soft blush',
    ],
    fontKey: 'fraunces',
    coordinate: {wght: 560, opsz: 48, SOFT: 80, WONK: 0},
    intense: {wght: 700, opsz: 72, SOFT: 100, WONK: 1},
    transform: 'none',
    alternateFontKeys: ['recursive', 'shantell', 'bricolage'],
    surface: 'warm',
    paletteId: 'neutral-elegance',
    specimenWord: 'Warm',
    reason: 'Soft, ink-wet Fraunces reads human and inviting.',
  },
  {
    id: 'clinical',
    label: 'Clinical',
    synonyms: [
      'precise',
      'neutral',
      'technical',
      'clear',
      'rational',
      'sterile',
      'system',
      'clinical',
      'clean',
      'minimal',
      'minimalist',
      'swiss',
      'corporate',
      'professional',
      'utilitarian',
      'functional',
      'objective',
      'scientific',
      'data',
      'dashboard',
      'modern ui',
      'sans',
      'geometric',
      'machine',
      'serenity',
      'trust',
      'focus',
      'health',
      'clarity',
      'ocean',
      'aquatic',
    ],
    fontKey: 'robotoFlex',
    coordinate: {wght: 460, wdth: 100, opsz: 18, GRAD: 0, slnt: 0},
    intense: {wght: 580, wdth: 95, opsz: 28, GRAD: 40, slnt: 0},
    transform: 'none',
    alternateFontKeys: ['bricolage', 'recursive', 'workbench'],
    surface: 'mist',
    paletteId: 'ocean-blue-serenity',
    specimenWord: 'Clear',
    reason: 'Neutral Roboto Flex at text optical size prioritizes clarity over personality.',
  },
  {
    id: 'nostalgic',
    label: 'Nostalgic',
    synonyms: [
      'vintage',
      'retro',
      'memory',
      'heritage',
      'old',
      'analogue',
      'analog',
      'weathered',
      'nostalgic',
      'nostalgia',
      'throwback',
      'antiquated',
      'antique',
      'typewriter',
      'letterpress',
      'faded',
      'past',
      'history',
      'historical',
      'old fashioned',
      'old-fashioned',
      'classic paper',
      'heirloom',
      'parchment',
      'manuscript',
      'soft vintage',
    ],
    fontKey: 'recursive',
    coordinate: {wght: 420, slnt: 0, CASL: 0.35, CRSV: 0, MONO: 0.85},
    intense: {wght: 550, slnt: -3, CASL: 0.6, CRSV: 0, MONO: 1},
    transform: 'none',
    alternateFontKeys: ['workbench', 'fraunces', 'shantell'],
    surface: 'warm',
    paletteId: 'neutral-elegance',
    specimenWord: 'Then',
    reason: 'Near-mono Recursive with casual lean evokes typewriter memory.',
  },
  {
    id: 'bold',
    label: 'Bold',
    synonyms: [
      'strong',
      'confident',
      'powerful',
      'assertive',
      'heavy',
      'impact',
      'loud',
      'bold',
      'boldness',
      'punchy',
      'poster',
      'headline',
      'heroic',
      'dominant',
      'commanding',
      'massive',
      'big',
      'brutal',
      'brutality',
      'impactful',
      'stark',
      'no nonsense',
      'fiery',
      'fire',
      'fierce',
      'molten',
      'lava',
      'passion',
      'passionate',
      'strength',
      'might',
      'mighty',
    ],
    fontKey: 'anybody',
    coordinate: {wght: 800, wdth: 120},
    intense: {wght: 900, wdth: 145},
    transform: 'uppercase',
    alternateFontKeys: ['nabla', 'bricolage', 'robotoFlex'],
    surface: 'ink',
    paletteId: 'fiery-ocean',
    specimenWord: 'BOLD',
    reason: 'Expanded Anybody fills the frame and refuses apology.',
  },
  {
    id: 'anxious',
    label: 'Anxious',
    synonyms: [
      'uneasy',
      'nervous',
      'restless',
      'edgy',
      'uncertain',
      'wired',
      'jittery',
      'anxious',
      'anxiety',
      'worried',
      'worry',
      'stressed',
      'stress',
      'panic',
      'panicky',
      'paranoid',
      'unstable',
      'glitchy',
      'glitch',
      'chaotic',
      'chaos',
      'overwhelmed',
      'tense nervous',
      'on edge',
      'mystery',
      'mysterious',
      'magnetic',
      'uncanny',
      'eerie',
      'shadowy',
      'twilight',
      'intrigue',
      'intriguing',
    ],
    fontKey: 'recursive',
    coordinate: {wght: 720, slnt: -10, CASL: 0.2, CRSV: 0.5, MONO: 0.4},
    intense: {wght: 900, slnt: -15, CASL: 0.5, CRSV: 1, MONO: 0.7},
    transform: 'none',
    alternateFontKeys: ['workbench', 'robotoFlex', 'shantell'],
    surface: 'dark',
    paletteId: 'magenta-dream',
    specimenWord: 'Wait',
    reason: 'Slanted Recursive with mixed mono/cursive edges feels slightly off-balance.',
  },
  {
    id: 'romantic',
    label: 'Romantic',
    synonyms: [
      'tender',
      'intimate',
      'elegant',
      'lyrical',
      'softhearted',
      'dreamy',
      'poetic',
      'romantic',
      'romance',
      'love',
      'loving',
      'sensual',
      'affectionate',
      'delicate',
      'graceful',
      'wedding',
      'valentine',
      'script',
      'flourish',
      'whisper',
      'passionate',
      'heartfelt',
      'magnetic',
      'allure',
      'alluring',
      'mysterious romance',
      'velvet',
      'plush',
      'opulent',
    ],
    fontKey: 'fraunces',
    coordinate: {wght: 300, opsz: 144, SOFT: 100, WONK: 1},
    intense: {wght: 450, opsz: 144, SOFT: 100, WONK: 1},
    italic: true,
    transform: 'none',
    alternateFontKeys: ['shantell', 'recursive', 'nabla'],
    surface: 'warm',
    paletteId: 'magenta-dream',
    specimenWord: 'Dear',
    reason: 'Wonky soft Fraunces italic leans intimate and lyrical.',
  },
]

export const DEFAULT_EMOTION_ID: EmotionId = 'calm'

/** Specimen size slider bounds (rem). */
export const SPECIMEN_SIZE_DEFAULT = 4.5
export const SPECIMEN_SIZE_MIN = 1.5
export const SPECIMEN_SIZE_MAX = 8
