/** Keys must match `SPECIMEN_FONTS` in `src/app/type-emotions/fonts.ts`. */
export type SpecimenFamilyKey =
  | 'cormorantGaramond'
  | 'libreBaskerville'
  | 'lora'
  | 'oswald'
  | 'bebasNeue'
  | 'anton'
  | 'fredoka'
  | 'nunito'
  | 'comfortaa'
  | 'playfairDisplay'
  | 'fraunces'
  | 'merriweather'
  | 'ibmPlexSans'
  | 'inter'
  | 'spaceGrotesk'
  | 'specialElite'
  | 'ebGaramond'
  | 'archivoBlack'
  | 'barlowCondensed'
  | 'syne'
  | 'jetbrainsMono'
  | 'greatVibes'

export type EmotionId =
  | 'calm'
  | 'urgent'
  | 'playful'
  | 'solemn'
  | 'warm'
  | 'clinical'
  | 'nostalgic'
  | 'bold'
  | 'anxious'
  | 'romantic'

export type EmotionAxes = {
  tracking: string
  leading: number
  transform: 'none' | 'uppercase'
}

export type EmotionFontRef = {
  familyKey: SpecimenFamilyKey
  /** Display label (Google Font family name). */
  label: string
  weight: number
}

import type {SpecimenPaletteId} from './palettes'

export type EmotionSurface = 'light' | 'mist' | 'warm' | 'dark' | 'ink'

export type EmotionEntry = {
  id: EmotionId
  label: string
  synonyms: string[]
  primary: EmotionFontRef
  alternates: EmotionFontRef[]
  axes: EmotionAxes
  /** Fallback chrome when no Coolors palette is set. */
  surface: EmotionSurface
  /** Optional Coolors-backed specimen palette (overrides surface vars). */
  paletteId?: SpecimenPaletteId
  specimenWord: string
  reason: string
}

export const EMOTION_CATALOG: EmotionEntry[] = [
  {
    id: 'calm',
    label: 'Calm',
    synonyms: [
      'peaceful',
      'serene',
      'quiet',
      'soft',
      'gentle',
      'tranquil',
      'relaxed',
      'calm',
      'calming',
      'mellow',
      'soothing',
      'still',
      'restful',
      'zen',
      'meditative',
      'balanced',
      'composed',
      'easygoing',
      'laid back',
      'chill',
      'peaceful quiet',
      'fuzzy',
      'fuzz',
      'plush',
      'cushioned',
      'hazy',
      'blurry',
      'cloud',
      'airy',
      'feathery',
      'muted soft',
      'subtle',
      'natural',
      'welcoming',
      'welcome',
      'understated',
      'elegant quiet',
      'collected',
      'timeless',
    ],
    primary: {familyKey: 'cormorantGaramond', label: 'Cormorant Garamond', weight: 400},
    alternates: [
      {familyKey: 'libreBaskerville', label: 'Libre Baskerville', weight: 400},
      {familyKey: 'lora', label: 'Lora', weight: 400},
    ],
    axes: {tracking: '0.02em', leading: 1.55, transform: 'none'},
    surface: 'light',
    paletteId: 'neutral-elegance',
    specimenWord: 'Calm',
    reason: 'Open serifs and soft contrast read quiet without going precious.',
  },
  {
    id: 'urgent',
    label: 'Urgent',
    synonyms: [
      'intense',
      'pressing',
      'loud',
      'alert',
      'immediate',
      'critical',
      'tense',
      'urgent',
      'urgency',
      'hurry',
      'rushed',
      'rush',
      'asap',
      'deadline',
      'breaking',
      'alarm',
      'alarming',
      'emergency',
      'crisis',
      'demanding',
      'insistent',
      'forceful',
      'high stakes',
      'time sensitive',
      'angry',
      'anger',
      'furious',
      'fury',
      'rage',
      'enraged',
      'mad',
      'irritated',
      'irate',
      'hostile',
      'hostility',
      'aggressive',
      'aggression',
      'wrath',
      'outraged',
      'pissed',
      'fiery',
      'fire',
      'flame',
      'flames',
      'burning',
      'heated',
      'hot',
      'volcanic',
    ],
    primary: {familyKey: 'oswald', label: 'Oswald', weight: 600},
    alternates: [
      {familyKey: 'bebasNeue', label: 'Bebas Neue', weight: 400},
      {familyKey: 'anton', label: 'Anton', weight: 400},
    ],
    axes: {tracking: '0.06em', leading: 1.15, transform: 'uppercase'},
    surface: 'dark',
    paletteId: 'fiery-ocean',
    specimenWord: 'NOW',
    reason: 'Condensed caps with tight leading push speed and insistence.',
  },
  {
    id: 'playful',
    label: 'Playful',
    synonyms: [
      'fun',
      'joyful',
      'whimsical',
      'lighthearted',
      'curious',
      'bouncy',
      'cheerful',
      'playful',
      'play',
      'happy',
      'happiness',
      'silly',
      'quirky',
      'cheeky',
      'lively',
      'upbeat',
      'bright',
      'sparkly',
      'bubbly',
      'comic',
      'carefree',
      'delightful',
      'kids',
      'childlike',
      'vibrant',
      'candy',
      'pop',
      'colorful',
      'zesty',
    ],
    primary: {familyKey: 'fredoka', label: 'Fredoka', weight: 500},
    alternates: [
      {familyKey: 'nunito', label: 'Nunito', weight: 700},
      {familyKey: 'comfortaa', label: 'Comfortaa', weight: 500},
    ],
    axes: {tracking: '0.01em', leading: 1.35, transform: 'none'},
    surface: 'mist',
    paletteId: 'candy-pop',
    specimenWord: 'Play',
    reason: 'Rounded terminals and medium weight feel friendly, not childish.',
  },
  {
    id: 'solemn',
    label: 'Solemn',
    synonyms: [
      'serious',
      'formal',
      'dignified',
      'grave',
      'ceremonial',
      'stately',
      'reverent',
      'solemn',
      'somber',
      'sombre',
      'funeral',
      'memorial',
      'respectful',
      'traditional',
      'classical',
      'institutional',
      'authoritative',
      'monumental',
      'weighty',
      'austere',
      'stoic',
      'dramatic',
      'drama',
      'theatrical',
      'evening',
      'twilight',
      'ceremonial drama',
    ],
    primary: {familyKey: 'playfairDisplay', label: 'Playfair Display', weight: 700},
    alternates: [
      {familyKey: 'cormorantGaramond', label: 'Cormorant Garamond', weight: 600},
      {familyKey: 'ebGaramond', label: 'EB Garamond', weight: 600},
    ],
    axes: {tracking: '0.01em', leading: 1.4, transform: 'none'},
    surface: 'mist',
    paletteId: 'magenta-dream',
    specimenWord: 'Solemn',
    reason: 'High-contrast display serifs carry ceremony and weight.',
  },
  {
    id: 'warm',
    label: 'Warm',
    synonyms: [
      'cozy',
      'inviting',
      'friendly',
      'human',
      'approachable',
      'earthy',
      'hospitable',
      'warm',
      'warmth',
      'welcoming',
      'comfort',
      'comfortable',
      'homey',
      'homely',
      'organic',
      'natural',
      'craft',
      'handmade',
      'amber',
      'sunset',
      'hearth',
      'subtle',
      'latte',
      'taupe',
      'soft blush',
    ],
    primary: {familyKey: 'fraunces', label: 'Fraunces', weight: 600},
    alternates: [
      {familyKey: 'merriweather', label: 'Merriweather', weight: 400},
      {familyKey: 'libreBaskerville', label: 'Libre Baskerville', weight: 400},
    ],
    axes: {tracking: '0em', leading: 1.5, transform: 'none'},
    surface: 'warm',
    paletteId: 'neutral-elegance',
    specimenWord: 'Warm',
    reason: 'Optical warmth in the serifs reads human and inviting.',
  },
  {
    id: 'clinical',
    label: 'Clinical',
    synonyms: [
      'precise',
      'neutral',
      'technical',
      'clear',
      'rational',
      'sterile',
      'system',
      'clinical',
      'clean',
      'minimal',
      'minimalist',
      'swiss',
      'corporate',
      'professional',
      'utilitarian',
      'functional',
      'objective',
      'scientific',
      'data',
      'dashboard',
      'modern ui',
      'sans',
      'geometric',
      'machine',
    ],
    primary: {familyKey: 'ibmPlexSans', label: 'IBM Plex Sans', weight: 500},
    alternates: [
      {familyKey: 'inter', label: 'Inter', weight: 500},
      {familyKey: 'spaceGrotesk', label: 'Space Grotesk', weight: 500},
    ],
    axes: {tracking: '0em', leading: 1.45, transform: 'none'},
    surface: 'mist',
    specimenWord: 'Clear',
    reason: 'Neutral neo-grotesques prioritize clarity over personality.',
  },
  {
    id: 'nostalgic',
    label: 'Nostalgic',
    synonyms: [
      'vintage',
      'retro',
      'memory',
      'heritage',
      'old',
      'analogue',
      'analog',
      'weathered',
      'nostalgic',
      'nostalgia',
      'throwback',
      'antiquated',
      'antique',
      'typewriter',
      'letterpress',
      'faded',
      'past',
      'history',
      'historical',
      'old fashioned',
      'old-fashioned',
      'classic paper',
      'heirloom',
      'parchment',
      'manuscript',
      'soft vintage',
    ],
    primary: {familyKey: 'specialElite', label: 'Special Elite', weight: 400},
    alternates: [
      {familyKey: 'ebGaramond', label: 'EB Garamond', weight: 400},
      {familyKey: 'libreBaskerville', label: 'Libre Baskerville', weight: 400},
    ],
    axes: {tracking: '0.03em', leading: 1.45, transform: 'none'},
    surface: 'warm',
    paletteId: 'neutral-elegance',
    specimenWord: 'Then',
    reason: 'Typewriter texture and classical serifs evoke memory.',
  },
  {
    id: 'bold',
    label: 'Bold',
    synonyms: [
      'strong',
      'confident',
      'powerful',
      'assertive',
      'heavy',
      'impact',
      'loud',
      'bold',
      'boldness',
      'punchy',
      'poster',
      'headline',
      'heroic',
      'dominant',
      'commanding',
      'massive',
      'big',
      'brutal',
      'brutality',
      'impactful',
      'stark',
      'no nonsense',
      'fiery',
      'fire',
      'fierce',
      'molten',
      'lava',
      'passion',
      'passionate',
      'strength',
      'might',
      'mighty',
    ],
    primary: {familyKey: 'archivoBlack', label: 'Archivo Black', weight: 400},
    alternates: [
      {familyKey: 'barlowCondensed', label: 'Barlow Condensed', weight: 700},
      {familyKey: 'anton', label: 'Anton', weight: 400},
    ],
    axes: {tracking: '0.02em', leading: 1.1, transform: 'uppercase'},
    surface: 'ink',
    paletteId: 'fiery-ocean',
    specimenWord: 'BOLD',
    reason: 'Heavy condensed forms fill the frame and refuse apology.',
  },
  {
    id: 'anxious',
    label: 'Anxious',
    synonyms: [
      'uneasy',
      'nervous',
      'restless',
      'edgy',
      'uncertain',
      'wired',
      'jittery',
      'anxious',
      'anxiety',
      'worried',
      'worry',
      'stressed',
      'stress',
      'panic',
      'panicky',
      'paranoid',
      'unstable',
      'glitchy',
      'glitch',
      'chaotic',
      'chaos',
      'overwhelmed',
      'tense nervous',
      'on edge',
      'mystery',
      'mysterious',
      'magnetic',
      'uncanny',
      'eerie',
      'shadowy',
      'twilight',
      'intrigue',
      'intriguing',
    ],
    primary: {familyKey: 'syne', label: 'Syne', weight: 700},
    alternates: [
      {familyKey: 'jetbrainsMono', label: 'JetBrains Mono', weight: 500},
      {familyKey: 'spaceGrotesk', label: 'Space Grotesk', weight: 700},
    ],
    axes: {tracking: '-0.02em', leading: 1.2, transform: 'none'},
    surface: 'dark',
    paletteId: 'magenta-dream',
    specimenWord: 'Wait',
    reason: 'Irregular proportions and mono edges feel slightly off-balance.',
  },
  {
    id: 'romantic',
    label: 'Romantic',
    synonyms: [
      'tender',
      'intimate',
      'elegant',
      'lyrical',
      'softhearted',
      'dreamy',
      'poetic',
      'romantic',
      'romance',
      'love',
      'loving',
      'sensual',
      'affectionate',
      'delicate',
      'graceful',
      'wedding',
      'valentine',
      'script',
      'flourish',
      'whisper',
      'passionate',
      'heartfelt',
      'magnetic',
      'allure',
      'alluring',
      'mysterious romance',
      'velvet',
      'plush',
      'opulent',
    ],
    primary: {familyKey: 'greatVibes', label: 'Great Vibes', weight: 400},
    alternates: [
      {familyKey: 'playfairDisplay', label: 'Playfair Display', weight: 400},
      {familyKey: 'cormorantGaramond', label: 'Cormorant Garamond', weight: 400},
    ],
    axes: {tracking: '0.01em', leading: 1.5, transform: 'none'},
    surface: 'warm',
    paletteId: 'magenta-dream',
    specimenWord: 'Dear',
    reason: 'Script flourish plus elegant serifs lean intimate and lyrical.',
  },
]

export const DEFAULT_EMOTION_ID: EmotionId = 'calm'

export const SCALE_SAMPLE =
  'Typography sets the emotional temperature of a page.'
